# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod Properties
version=1.0.0
group=com.sft

# Dependencies
fabric_api_version=0.155.3+26.1.2
owo_version=0.13.1+26.1
mod_menu_version=9PxiZuDD
custom_durability=2RxN9Js8
alloyed=xhkBG1pk
text_placeholder_api=b3IPAHgB
create_fly=wV5IQLKg
architectury=k9DCEQ4B
cloth_config=GFM8zh9J
enderite=Fh7UkpCU